- .spelling
- docs/user/imports/csv.md
- mkdocs.yml
Added CSV Import
Short explanation of the functionalities of the CSV Import
-   CSV Import
-   Spelling file
-   Navigation
By sending this pull request I have read and accept the following conditions:
-   [x ] I have read the [code of conduct](../CODE_OF_CONDUCT.md) and accept it.
-   [ x] I have read the [contributing guidelines](../CONTRIBUTING.md) and accept them.
-   [ x] I have read the [writing guidelines](../GUIDELINES.md) and accept them.
-   [ x] I accept that my contribution will be licensed under a [CC BY-SA 4.0 License](../LICENSE).
> Csv import

- .alexrc.yaml
- .markdownlint.json
- .spelling
Add words to spelling files for preparation to Update-2.2.0 branch
Add all necessary words from the Changelog's to spelling files.
Without this the Pull request is not possible
-   Create markdownlint.json
-   Add words to .alexrc.yaml 
-   Add words to.spelling words
By sending this pull request I have read and accept the following conditions:
-   [ X] I have read the [code of conduct](../CODE_OF_CONDUCT.md) and accept it.
-   [ X] I have read the [contributing guidelines](../CONTRIBUTING.md) and accept them.
-   [ X] I have read the [writing guidelines](../GUIDELINES.md) and accept them.
-   [ X] I accept that my contribution will be licensed under a [CC BY-SA 4.0 License](../LICENSE).
> Fixing spelling files for update branch 2.2.0

- .spelling
- docs/ref/changelog.md
- docs/ref/release-notes/v2.2.5.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.2.5
- Add changelog of v2.2.5
- Add v2.2.5 to version history
> Release v2.2.5

- announcements.py
- data/announcements.yml
- docs/announcements.md
- mkdocs.yml
- requirements.txt
- templates/announcements.atom.j2
- theme/main.html
- Add first announcement about the public beta
- Add page
- Add Atom feed
- Add feeds as meta data to each page
- Remove unused RSS plugin
> Publish announcements

- docs/user/basics/objects.md
> Om 20 object ranking

- docs/ref/changelog.md
- docs/ref/release-notes/v2.2.6.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.2.6
- Add changelog of v2.2.6
- Add v2.2.6 to version history
> Release v2.2.6

- docs/ref/changelog.md
- docs/ref/release-notes/v2.2.7.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.2.7
- Add changelog of v2.2.7
- Add v2.2.7 to version history
> Release v2.2.7

- docs/admin/users-groups-roles.md
Short password complexity
Long description described the password complexity rules
> Om 26 login password validation

- docs/user/usecases/quick-edit-in-lists.md
- mkdocs.yml
Added Use Case for quick edit in lists.
Edited navigation to make Use Case show up
> Om 38 uc quick edit in list

- .alexrc.yaml
- .spelling
- docs/user/usecases/how-to-start.md
- mkdocs.yml
Added use case for how to start.
Edited navigation to make Use Case show up
> om-39-how-to-start

- docs/user/basics/menubar.md
- mkdocs.yml
> Om 32 menu

- docs/user/basics/enable-disable-attributes.md
- mkdocs.yml
Added navigation.
Added doc to basics.
> Om 4 activating deactivating attributes

- Dockerfile-ci
- mkdocs.yml
- package-lock.json
- requirements.txt
…of…
- Material for MkDocs
- Docker Compose
- editorconfig-checker
- yamllint
- NPM dependencies
> Bump versions

- docs/index.md
> Edit about and deactivate Snow

- .alexrc.yaml
- mkdocs.yml
Fixed typo in navigation
Added easy to alexignore
> Fix typo in nav and added easy to alexingore

- docs/user/usecases/rights-assignment.md
> Rights assignment fix

- docs/ref/changelog.md
- docs/ref/release-notes/v2.0.1.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.0.1
- Add changelog of v2.0.1
- Add v2.0.1 to version history
> Release v2.0.1

- docs/ref/changelog.md
- docs/ref/release-notes/v2.1.0.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.1.0
- Add changelog of v2.1.0
- Add v2.1.0 to version history
> Release v2.1.0

- docs/ref/changelog.md
- docs/ref/release-notes/v2.2.0.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.2.0
- Add changelog of v2.2.0
- Add v2.2.0 to version history
> Release v2.2.0

- docs/ref/changelog.md
- docs/ref/release-notes/v2.2.1.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.2.1
- Add changelog of v2.2.1
- Add v2.2.1 to version history
> Release v2.2.1

- docs/ref/changelog.md
- docs/ref/release-notes/v2.3.0.md
- docs/ref/version-history.md
- docs/releases.atom
- Add release notes of v2.3.0
- Add changelog of v2.3.0
- Add v2.3.0 to version history
> Release v2.3.0

- docs/ref/changelog.md
- docs/ref/release-notes/v2.3.1.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.3.1**
- **Add changelog of v2.3.1**
- **Add v2.3.1 to version history**
> Release v2.3.1

- docs/ref/changelog.md
- docs/ref/release-notes/v2.3.2.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.3.2**
- **Add changelog of v2.3.2**
- **Add v2.3.2 to version history**
> Release v2.3.2

- docs/ref/changelog.md
- docs/ref/release-notes/v2.3.3.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.3.3**
- **Add changelog of v2.3.3**
- **Add v2.3.3 to version history**
> Release v2.3.3

- docs/ref/changelog.md
- docs/ref/release-notes/v2.4.0.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.4.0**
- **Add changelog of v2.4.0**
- **Add v2.4.0 to version history**
> Release v2.4.0

- docs/ref/changelog.md
- docs/ref/release-notes/v2.5.0.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.5.0**
- **Add changelog of v2.5.0**
- **Add v2.5.0 to version history**
> Release v2.5.0

- .config/remark.json
[fix(chore): Fixed option for dead urls
> fix(chore): Fixed option for dead urls

- docs/ref/changelog.md
- docs/ref/release-notes/v2.6.1.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.6.1**
- **Add changelog of v2.6.1**
- **Add v2.6.1 to version history**
> Release v2.6.1

- docs/ref/changelog.md
- docs/ref/release-notes/v2.6.2.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.6.2**
- **Add changelog of v2.6.2**
- **Add v2.6.2 to version history**
> Release v2.6.2

- docs/ref/changelog.md
- docs/ref/release-notes/v2.6.3.md
- docs/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.6.3**
- **Add changelog of v2.6.3**
- **Add v2.6.3 to version history**
> Release v2.6.3

- docs/admin/servereye.md
Improve clarity and accuracy in the servereye integration documentation, including adjustments to the synchronization process and login instructions.
> Update servereye integration documentation for clarity

- Dockerfile
- README.md
- SUPPORT.md
- docs/de/dev/addon/introduction.md
- docs/de/index.md
- docs/en/dev/addon/introduction.md
- docs/en/index.md
- docs/en/security.md
- i18n/de/spelling.txt
- i18n/en/spelling.txt
- i18n/mkdocs.yml
- package-lock.json
- package.json
- static/humans.txt
- web/Dockerfile
synetics is dead.
Long live i-doit!
> Rename company to `i-doit GmbH`

- docs/en/ref/changelog.md
- docs/en/ref/release-notes/v2.8.0.md
- docs/en/ref/version-history.md
- docs/releases.atom
- **Add release notes of v2.8.0**
- **Add changelog of v2.8.0**
- **Add v2.8.0 to version history**
> Release v2.8.0
